version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:14.1
    expose:
      - '5432'
  redis:
    restart: always
    image: redis:6.2
    expose:
      - '6379'
  app:
    environment:
      SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      REDIS_URL: redis://redis
      DJANGO_SETTINGS_MODULE: bakerydemo.settings.production
      WAGTAILADMIN_BASE_URL: http://localhost:8005/admin/
      SECURE_HSTS_SECONDS: 0
      SECURE_SSL_REDIRECT: false
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - '8005:8005'
    depends_on:
      - db
      - redis