---
name: Bakerydemo GOLD benchmark
author: Didi Hoffmann <didi@green-coding.org>
version: 1
architecture: linux

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:14.1
    expose:
      - '5432'
    networks:
      - bakery-bench-green-coding-network
    # we need the DB fully booted. Therefore we wait here a little
    setup-commands:
      - sleep 10

  redis:
    restart: always
    image: redis:6.2
    expose:
      - '6379'
    networks:
      - bakery-bench-green-coding-network

  app:
    environment:
      SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      REDIS_URL: redis://redis
      DJANGO_SETTINGS_MODULE: bakerydemo.settings.production
      WAGTAILADMIN_BASE_URL: http://app:8005/admin/
      SECURE_HSTS_SECONDS: 0
      SECURE_SSL_REDIRECT: false
    image: bakerydemo-gold-benchmark-app
    links:
      - db:db
      - redis:redis
    ports:
      - '8005:8005'
    depends_on:
      - db
      - redis
    networks:
      - bakery-bench-green-coding-network
    setup-commands:
      - ./manage.py migrate
      - ./manage.py load_initial_data
      - wget --recursive --spider --no-directories http://app:8005/ -o warmup.log

  green-coding-puppeteer-container:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/benchmark/puppeteer/admin.js /var/www/admin.js
    networks:
      - bakery-bench-green-coding-network


flow:
  - name: Check dynamic Website
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command:  node /var/www/admin.js
        note: Starting admin Flow
        read-notes-stdout: true

networks:
  bakery-bench-green-coding-network:
