---
name: Bakerydemo GOLD benchmark Static
author: Danilo Ješić <danilo@green-coding.berlin>
version: 1
description: Testing all routes of the exemplary Bakery demo Gold Benchmark
compose-file: !include docker-compose.yml

services:
  db:
    networks:
      - bakery-bench-green-coding-network
    # we need the DB fully booted. Therefore we wait here a little
    setup-commands:
      - sleep 1
    pause-after-phase: '[BOOT]' #Phase names are always in []

  redis:
    networks:
      - bakery-bench-green-coding-network
    pause-after-phase: '[BOOT]'

  app:
    environment:
      WAGTAILADMIN_BASE_URL: http://app:8005/admin/
    image: bakerydemo-gold-benchmark-app
    networks:
      - bakery-bench-green-coding-network
    setup-commands:
      - ./manage.py migrate
      - ./manage.py load_initial_data
    pause-after-phase: '[BOOT]'

  static_app:
    networks:
      - bakery-bench-green-coding-network
    volumes: []
    setup-commands:
      - apt update
      - apt install wget
      - wget --mirror http://app:8005/ -P /tmp || true
      - cp -R /tmp/app:8005/* /usr/share/nginx/html/


  green-coding-puppeteer-container:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/benchmark/puppeteer/blog-filtering.js /var/www/blog-filtering.js
      - cp /tmp/repo/benchmark/puppeteer/homepage-landing.js /var/www/homepage-landing.js
      - cp /tmp/repo/benchmark/puppeteer/package.json /var/www/package.json

    networks:
      - bakery-bench-green-coding-network

flow:
  - name: Check blog-filtering
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=http://static_app:80 node /var/www/blog-filtering.js
        note: Starting admin Flow
        read-notes-stdout: false
  - name: Check homepage landing
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=http://static_app:80 node /var/www/homepage-landing.js
        note: Starting admin Flow
        read-notes-stdout: false

networks:
  bakery-bench-green-coding-network:
